### ISSUE TITLE
Certificate Requests stop if one certificate is already issued

### ISSUE THREAD

**Issue by Muirrum** [geerlingguy/ansible-role-certbot#113]
Given a `domains` list of two or more domains, if one of the domains already has a certificate issued, the others won't be issued because certbot will stop processing.

**Comment by guix77** [comment]
You can comment the domain which already has a cert. Dunnow if the renewal works fine, though.

**Comment by choice-webdev** [comment]
:+1:

**Comment by sashasaturn** [comment]
I can confirm such strange behavior ....

**Comment by LordAro** [comment]
Also ran into this. Looks like the role is just taking the first certificate, so I guess a workaround is to always prepend to that list?
https://github.com/geerlingguy/ansible-role-certbot/blob/fe1716eced1fe29de791122a29f5420d6529e4d0/tasks/create-cert-standalone.yml#L2-L5

Doesn't seem *too* difficult to make it operate on all elements of the list, rather than just the first

**Comment by LordAro** [comment]
Ah, after prepending I run into:

>fatal: [bananas-2.cdn.openttd.org]: FAILED! => {"changed": true, "cmd": ["certbot", "certonly", "--standalone", "--noninteractive", "--agree-tos", "--email", "info@openttd.org", "-d", "newdomain.org,olddomain.org"]...


>Saving debug log to /var/log/letsencrypt/letsencrypt.log
>Plugins selected: Authenticator standalone, Installer None
>Missing command line flag or config entry for this setting:
>You have an existing certificate that contains a portion of the domains you requested (ref: /etc/letsencrypt/renewal/bananas-2.cdn.openttd.org.conf)
>
>It contains these names: bananas-2.cdn.openttd.org
>
>You requested these names for the new certificate: newdomain.org, olddomain.org.
>
>Do you want to expand and replace this existing certificate with the new certificate?
>
>(You can set this with the --expand flag)
