### ISSUE TITLE
trouble testing with molecule

### ISSUE THREAD

**Issue by parisni** [geerlingguy/ansible-role-certbot#140]
hi,

I am having this error while testing the role:

```bash
git clone git@github.com:geerlingguy/ansible-role-certbot.git
cd ansible-role-certbot
molecule test
[....]
INFO     Running default > syntax
ERROR! the role 'geerlingguy.certbot' was not found in /home/parisni/git/ansible-certbot/molecule/default/roles:/home/parisni/.cache/molecule/ansible-certbot/default/roles:/home/parisni/git:/home/parisni/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/parisni/git/ansible-certbot/molecule/default

The error appears to be in '/home/parisni/git/ansible-certbot/molecule/default/converge.yml': line 27, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - geerlingguy.certbot
      ^ here

```

Also I am very curious about the   `certbot-test.servercheck.in` certs. Am I supposed to provide some cert in order the test work ?

**Comment by mpkayeuk** [comment]
Yep, I'm also experiencing this.  I follow Jeff because he's basically my goto guy for Ansible best practices (huge thanks for your work Jeff).  I thought this was something to do with the galaxy metadata and that molecule should figure out the role name from that, but I don't think that's the case.  I think this has more to do with GitHub Actions and the fact that the code is checked out into a directory named the same as the Galaxy name.

Presumably, Jeff has some symlinking, or something, going on in his local setup for Molecule to work there.  For example, if you do this:

`ln -s ansible-role-certbot geerlingguy.certbot`

This fixes the problem and Molecule can happily converge, but it's a touch cumbersome.

Can you shed any light on this @geerlingguy?  Guidance would be hugely appreciated, and sorry if these are dumb questions.

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/ansible-role-certbot/blob/master/.github/workflows/ci.yml#L13

That tells GitHub actions to check out this project into the directory `geerlingguy.certbot`, and then molecule works correctly with it.
