### ISSUE TITLE
Build in support for Nginx and autorenewal

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/ansible-role-certbot#2]
Maybe use https://github.com/diafygi/acme-tiny?

**Comment by 030** [comment]
What about just running

```
letsencrypt renew 
```

**Comment by enricostano** [comment]
I would like to give a try solving this. What's the plan on installing plugins? Should we first think about how do we want to manage plugins?

The general idea could be:
1. Make it possible to install more recent versions (e.g. using PPA like in https://github.com/geerlingguy/ansible-role-certbot/pull/32)
2. Store in a variable the list of plugins to install (e.g. `certbot_plugins`, empty by default)
3. Install package for each plugin (e.g. `certbot-nginx`)
4. Create certificates with `certonly --nginx` (this will NOT modify nginx configuration)
5. Renew as usual with just `renew`, `certbot-nginx` plugin will deal with nginx servers

#### Notes
 - Point `1` and `3` may change installing `certbot-auto` via sources
 - This approach requires a custom Nginx configuration to add in the role that manages Nginx server blocks (e.g. https://wiki.archlinux.org/index.php/Let%E2%80%99s_Encrypt#Managing_server_blocks)

What do you think?

**Comment by colans** [comment]
This is still an issue.

**Comment by ericsysmin** [comment]
I've added plugin support, so you can have plugin installed, however, you will still need to modify the cerbot command https://github.com/geerlingguy/ansible-role-certbot/pull/108

**Comment by colans** [comment]
This is still an issue.

**Comment by colans** [comment]
This is still an issue.

**Comment by colans** [comment]
This is still an issue.

**Comment by colans** [comment]
👋

**Comment by colans** [comment]
:wave:

**Comment by colans** [comment]
:wave:

**Comment by colans** [comment]
:wave:

**Comment by sgutermann** [comment]
I am not sure on what the actual problem is trying to be solved here. If you use the standalone option you get your cert. What you do with it should be up to you and your ansible.

If this is about the cronjob not working as the apache or nginx or whatever is still running then the quick fix would be to ad the pre and post hook.

Really unclean example would be: 

`"{{ certbot_script }} renew {{ certbot_auto_renew_options }} --pre-hook='systemctl stop {{ certbot_create_standalone_stop_services }}' --post-hook='systemctl start {{ certbot_create_standalone_stop_services }}'"
`

Like I said "unclean" as the var was intented for the first install according to the README.

**Comment by colans** [comment]
Thanks for confirming.  This looks close enough to what I came up with for our [Matomo role](https://galaxy.ansible.com/consensus/matomo), but I specified it in the domain config instead (which seems cleaner).  See [the commit](https://gitlab.com/consensus.enterprises/ansible-roles/ansible-role-matomo/-/commit/3cc7b4d51c2a21ce1a841966a84bb37938b1299d) for details.

I suppose we can close this then.  (I'd do it, but I don't see a button for that.)
