### ISSUE TITLE
Fix installation using package manager on Debian 8

### ISSUE THREAD

**Issue by pkoziol** [geerlingguy/ansible-role-certbot#25]
Package certbot is currently available [only in jessie-backports](https://packages.debian.org/jessie-backports/certbot) on Debian 8. That means certbot installation using package manager requires configuring that repository first - I used role [jnv.debian-backports](https://galaxy.ansible.com/jnv/debian-backports/) for that. It would be great if this role did it automatically or it was mentioned in the docs.

It also requires specifying default release for apt - I just replaced line:
`package: "name={{ certbot_package }} state=present"`
with:
`apt: "name={{ certbot_package }} default_release=jessie-backports state=present"`
in [tasks/install-with-package.yml](https://github.com/geerlingguy/ansible-role-certbot/blob/01d801c4b71cb6e345e89622b142049da40b1017/tasks/install-with-package.yml#L3), but it is not very portable I guess.

**Comment by styks1987** [comment]
The documentation addresses this pretty clearly from what I can see. You should be installing from the sources on jessie, the install time is very short and works without messing with the sources list which IMO always gets forgotten.

https://github.com/geerlingguy/ansible-role-certbot#source-installation-from-git

**Comment by avra911** [comment]
installing from source still needs `apt: "name=python-ndg-httpsclient default_release=jessie-backports state=present"`

**Comment by pm5** [comment]
The documentation says source installation might be desired for Debian < 8, which seems to me suggests that it's not required on Debian 8, but it is unless you have jessie-backports.

I think it would be better if the documentation is change to something like "Debian < 8 or Debian 8 without backports"?

**Comment by geerlingguy** [comment]
See commit linked above ^

Basically, if you're on any OS older than the latest generation of Ubuntu/CentOS/Debian/etc., then I'd recommend using the source install instead of the package install.

Alternatively, in the future this role might use the upstream package repository instead of the OS repos, meaning the package install would (or at least _should_) install a much more recent version. And in Debian 8's case... one that actually is able to be installed since it would exist :D
