### ISSUE TITLE
letsencrypt: error: unrecognized arguments: --quiet

### ISSUE THREAD

**Issue by salamachinas** [geerlingguy/ansible-role-certbot#28]
Getting error: letsencrypt: error: unrecognized arguments: --quiet

```bash
root@some-server:/tmp# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
```

```bash
root@some-server:/tmp# letsencrypt --version
letsencrypt 0.4.1
```

**Comment by geerlingguy** [comment]
@salamachinas - If you're using Ubuntu 16.04, see:

  - https://community.letsencrypt.org/t/quiet-missing-from-ubuntu-package-letsencrypt-client/20857
  - https://bugs.launchpad.net/ubuntu/+source/python-letsencrypt/+bug/1610030

It seems the version Ubuntu's repos are pointed at (0.4.1) has a few bugs... and will also stop working entirely at some point :/

I'm using certbot on CentOS 7 mainly, so I haven't hit this issue before... and since the automated tests don't try using the `--quiet` option, they aren't picking it up either.

**Comment by geerlingguy** [comment]
Also, you can now override the flags passed to the certbot-auto command; see #35 

Closing this issue for now.

**Comment by dsteinkopf** [comment]
So what is the proposed solution for this problem? Remove `--quiet` from `certbot_auto_renew_options` ? So the cronjob will send a useless email every time. Any better idea?

**Comment by dsteinkopf** [comment]
The answer can be found in https://galaxy.ansible.com/geerlingguy/certbot/: "Source Installation from Git". This is proposed for e.g. Ubunutu < 16.10. So adding `certbot_install_from_source: yes` solved the problem for me.
