### ISSUE TITLE
Certbot & Geerlingguy Nginx

### ISSUE THREAD

**Issue by jasperf** [geerlingguy/ansible-role-certbot#29]
I just installed this Ansible certbot playbook for my [Laravel Lemp Playbooks Stedding](https://github.com/jasperf/stedding/). Then I had to move on integrating it with Nginx. For that I use your playbook for Nginx as well. I realized doing 
````
apt install python-certbot-nginx
````
and then run the Certbot plugin using:
````
certbot --nginx
````
took care of everything. Only now when I run my whole package Nginx will overwrite all this with what I have now in vhost and the standard nginx.conf. So I guess I could setup a separate template called `roles/nginx/templates/domain`. Then I could call it inside my `vars/main.yml` with
````
nginx_conf_template: "{{ playbook_dir }}/templates/my.conf.j2"
````
Then to make it extend the basic nginx.conf I could add
````
{% extends 'roles/geerlingguy.nginx/templates/nginx.conf.j2' %}
````
At least I think this would be the way. And then add the details. But how? 

Certbot now added:
````
listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/domain.com,/fullchain.pem; # managed by Certbot
ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot
ssl_session_cache shared:le_nginx_SSL:1m; # managed by Certbot
ssl_session_timeout 1440m; # managed by Certbot

ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # managed by Certbot
ssl_prefer_server_ciphers on; # managed by Certbot

ssl_ciphers "xxxxxxx"; # managed by Certbot



    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    } # managed by Certbot

}
````
And when I provision again this will now be wiped out due to the basic nginx.conf settings. And that I do not want..
Should I just add that code as Certbot added and use my {{ domain }} variable there to load the domain path? I  do not think that is quite it... I mean, the  `ssl_ciphers` that I would generate using `certbot only` would also have to be added somehow..right?

***Update**
Other option would be of course to add another post LEMP installation task and just 
````
apt install python-certbot-nginx
````
and then run the Certbot plugin using:
````
certbot --nginx
````
That would install things again. And as long as this does not happen too often the certificates should be added and working without any issues. Did see in Root Trelllis though that it is all managed with Ansible and I would prefer that. And that gets me back to the first option.

**Comment by geerlingguy** [comment]
@jasperf - You've encountered the infamous chicken-and-egg problem with SSL certs :)

This role can handle certificate generation now, as of https://github.com/geerlingguy/ansible-role-certbot/pull/38 (version 3.0.0), and I'd recommend doing everything through this role instead of using `certbot --nginx`.

Alternatively, if you use `certbot --nginx --cert-only` (I think that's the flag), it will just generate the flag and not mess with your Nginx configuration. I generally frown on tools like certbot touching configuration, since I'd rather manage/optimize/change that _myself_.

Especially look through the new example playbook in this role's `tests/` directory for a perfect example of using the Nginx role + this role for 100% automated cert generation: https://github.com/geerlingguy/ansible-role-certbot/blob/master/tests/test-standalone-nginx-aws.yml
