### ISSUE TITLE
Error on renewal on Ubuntu 16.04

### ISSUE THREAD

**Issue by AjkP** [geerlingguy/ansible-role-certbot#47]
I am trying to run renewal manually, to see if it's actually running and unfortunately it's erring :/

When running:
`sudo /opt/certbot/certbot-auto renew --quiet --no-self-upgrade`

Im getting the following stacktrace:

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 719, in main
    symlink=options.symlink)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 988, in create_environment
    download=download,
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 918, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/lib/python3/dist-packages/virtualenv.py", line 812, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /opt/eff.org/certbot/venv/bin/python2.7 - setuptools pkg_resources pip wheel failed with error code 1
```

It seems to be related to [certbot issue #2883](https://github.com/certbot/certbot/issues/2883).

**Comment by M-Devloo** [comment]
This problem is still active for Certbot. (17/10/2018)

Currently there is no straight solution for Ubuntu 16.04, only workarounds.
* Source -> Use the export LC_ALL & LC_CTYPE (See [Issue #2883](https://github.com/certbot/certbot/issues/2883))
* Package -> Use the PPA, else you get a outdated letsencrypt (See [Certbot Ubuntu 16.04](https://docs.ansible.com/ansible/latest/modules/apt_repository_module.html))

_Package_
When installing the 'latest' letsencrypt through apt-get will give you still Version 0.4.1-1 (Release March 2016) while the latest version is already v0.27.1 (time of writing of this port), it is mandatory to install it through source.

When running it from source, it will give you the above error. Meaning if you perform a fresh deploy, your certificates will never be renewed. (It will silently fail)

According to the Certbot site, it is suggested to install the Certbot PPA for Ubuntu 16.04
> https://certbot.eff.org/lets-encrypt/ubuntuxenial-nginx (Nginx example) 

The PPA could be one version behind (Testing on a baremetal Ubuntu 16.04 machine, it is version 0.26.1)

It should be possible to add this through the "apt_repository" ansible command
> (https://docs.ansible.com/ansible/latest/modules/apt_repository_module.html)

A new task could install this PPA when Ubuntu 16.04 is detected as OS. But it is merely a workaround until #2883 is fixed (which won't be in a while).

_Source_
As stated in the issue #2883, exporting LC_ALL & LC_CTYPE environment variable will fix the issue and allows you to continue forward. Although this means that you have to execute this for every fresh server.

**Comment by M-Devloo** [comment]
_Package Ubuntu 18.04_
For Ubuntu 18.04, i have also noticed that another bug is open when installing it from the default packages (https://github.com/certbot/certbot/issues/6362). Meaning for a **fresh install** the command `sudo add-apt-repository universe` will have to be added, else the installation will fail due to 'unmet dependencies'

Although i haven't tried it installing from source for Ubuntu 18.04 yet.
